language: node_js

# test on the latest node js version
node_js:
  - "node"

after_success:
- npm run coveralls

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!